# Generated by Django 2.2.4 on 2020-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('m', 'Mobile'), ('Lp', 'LapTop'), ('E', 'Electronics')], max_length=2),
        ),
    ]
